export const mockProcedureTypes = [
  { uuid: 'pt-uuid-1', name: 'Surgery' },
  { uuid: 'pt-uuid-2', name: 'Endoscopy' },
  { uuid: 'pt-uuid-3', name: 'Radiology' },
];

export const searchedProcedure = [{ uuid: 'proc-concept-uuid-1', display: 'Appendectomy' }];

export const mockProceduresResponse = {
  results: [
    {
      uuid: 'proc-uuid-1',
      display: 'Appendectomy',
      procedureCoded: { display: 'Appendectomy' },
      procedureType: { name: 'Surgery' },
      bodySite: { display: 'Abdomen' },
      startDateTime: '2021-01-10T00:00:00.000+0000',
      endDateTime: '2021-01-10T02:00:00.000+0000',
      duration: 45,
      durationUnit: { display: 'Minutes' },
      notes: 'Procedure went well',
      status: { display: 'Completed' },
      voided: false,
    },
    {
      uuid: 'proc-uuid-2',
      display: 'Colonoscopy',
      procedureCoded: { display: 'Colonoscopy' },
      procedureType: { name: 'Endoscopy' },
      bodySite: { display: 'Colon' },
      startDateTime: '2021-02-15T00:00:00.000+0000',
      status: { display: 'Completed' },
      voided: false,
    },
    {
      uuid: 'proc-uuid-3',
      display: 'Blood draw',
      procedureNonCoded: 'Blood draw',
      procedureType: { name: 'Lab' },
      bodySite: { display: 'Arm' },
      startDateTime: '2021-03-20T00:00:00.000+0000',
      status: { display: 'Completed' },
      voided: false,
    },
    {
      uuid: 'proc-uuid-4',
      display: 'Chest X-Ray',
      procedureCoded: { display: 'Chest X-Ray' },
      procedureType: { name: 'Radiology' },
      bodySite: { display: 'Chest' },
      startDateTime: '2021-04-05T00:00:00.000+0000',
      status: { display: 'Completed' },
      voided: false,
    },
    {
      uuid: 'proc-uuid-5',
      display: 'ECG',
      procedureCoded: { display: 'ECG' },
      procedureType: { name: 'Cardiology' },
      bodySite: { display: 'Heart' },
      startDateTime: '2021-05-12T00:00:00.000+0000',
      status: { display: 'Completed' },
      voided: false,
    },
    {
      uuid: 'proc-uuid-6',
      display: 'MRI Brain',
      procedureCoded: { display: 'MRI Brain' },
      procedureType: { name: 'Radiology' },
      bodySite: { display: 'Brain' },
      startDateTime: '2021-06-18T00:00:00.000+0000',
      status: { display: 'Completed' },
      voided: false,
    },
    {
      uuid: 'proc-uuid-7-voided',
      display: 'Should Not Appear',
      procedureCoded: { display: 'Should Not Appear' },
      procedureType: { name: 'Surgery' },
      bodySite: { display: 'Abdomen' },
      startDateTime: '2021-07-01T00:00:00.000+0000',
      status: { display: 'Completed' },
      voided: true,
    },
  ],
  links: [],
};
